version: "3.8"

services:

  golang-api-template:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
    tty: true
    environment:
      - CFG_SERVE_PUBLIC_PORT=8080
      - CFG_SERVE_TRACING_URL=http://jaeger:14268/api/traces
      # - CFG_PATH=/app/config.yml
    volumes:
        # Source code
      - .:/app
    ports:
      - 8080:8080
    restart: on-failure

  # Visualizer for metrics and traces
  grafana:
    image: grafana/grafana:8.1.5
    environment:
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    ports:
      - "3000:3000"
    #volumes:
    #  - ./config/grafana/provisioning:/etc/grafana/provisioning
    restart: on-failure

  # Metrics collector
  prometheus:
    image: prom/prometheus:v2.12.0
    ports:
      - "9090:9090"
    command:
      --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./config/prometheus/config.yml:/etc/prometheus/prometheus.yml
    restart: on-failure

  # Trace collector
  jaeger:
    image: jaegertracing/all-in-one:1.26
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    restart: on-failure
